/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Seguridad;

import Datos.Conexion;
import Datos.ListaEleccion;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Paul
 */
public class Administrador extends javax.swing.JDialog {
    private String accion;
    public Conexion enlace;
    public Administradores padre;
    
    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lcodigo = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        ldescri = new javax.swing.JLabel();
        boton_guardar = new javax.swing.JButton();
        boton_cancelar = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        lapellido = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        ltelefono = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        lemail1 = new javax.swing.JLabel();
        email1 = new javax.swing.JTextField();
        lemail2 = new javax.swing.JLabel();
        email2 = new javax.swing.JTextField();
        llogin = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        lpassword = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        status = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrador");
        setMinimumSize(new java.awt.Dimension(580, 200));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setPreferredSize(new java.awt.Dimension(580, 200));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(null);

        lcodigo.setText("ID");
        getContentPane().add(lcodigo);
        lcodigo.setBounds(20, 40, 70, 14);

        nombre.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        nombre.setMinimumSize(new java.awt.Dimension(8, 24));
        nombre.setPreferredSize(new java.awt.Dimension(8, 24));
        getContentPane().add(nombre);
        nombre.setBounds(170, 60, 220, 28);

        ldescri.setText("Nombre");
        getContentPane().add(ldescri);
        ldescri.setBounds(170, 40, 120, 14);

        boton_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuardarTodo.png"))); // NOI18N
        boton_guardar.setMnemonic('G');
        boton_guardar.setText("OK");
        boton_guardar.setToolTipText("Guardar registro");
        boton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_guardar);
        boton_guardar.setBounds(400, 260, 130, 40);

        boton_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        boton_cancelar.setMnemonic('C');
        boton_cancelar.setText("Cancelar");
        boton_cancelar.setToolTipText("Cancelar actualización");
        boton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_cancelar);
        boton_cancelar.setBounds(540, 260, 130, 40);

        id.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        id.setMinimumSize(new java.awt.Dimension(8, 24));
        id.setPreferredSize(new java.awt.Dimension(8, 24));
        getContentPane().add(id);
        id.setBounds(20, 60, 70, 28);

        lapellido.setText("Apellido");
        getContentPane().add(lapellido);
        lapellido.setBounds(400, 40, 90, 14);
        getContentPane().add(apellido);
        apellido.setBounds(400, 60, 280, 28);

        ltelefono.setText("Telefono");
        getContentPane().add(ltelefono);
        ltelefono.setBounds(20, 110, 60, 14);
        getContentPane().add(telefono);
        telefono.setBounds(20, 130, 140, 28);

        lemail1.setText("Email 1");
        getContentPane().add(lemail1);
        lemail1.setBounds(170, 110, 60, 14);
        getContentPane().add(email1);
        email1.setBounds(170, 130, 220, 28);

        lemail2.setText("Email 2");
        getContentPane().add(lemail2);
        lemail2.setBounds(400, 110, 60, 14);
        getContentPane().add(email2);
        email2.setBounds(400, 130, 280, 28);

        llogin.setText("Login");
        getContentPane().add(llogin);
        llogin.setBounds(20, 180, 50, 14);
        getContentPane().add(login);
        login.setBounds(20, 200, 140, 28);

        lpassword.setText("Password");
        getContentPane().add(lpassword);
        lpassword.setBounds(170, 180, 80, 14);

        password.setText("jPasswordField1");
        getContentPane().add(password);
        password.setBounds(170, 200, 150, 28);

        status.setText("Activo");
        getContentPane().add(status);
        status.setBounds(400, 200, 55, 28);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-723)/2, (screenSize.height-352)/2, 723, 352);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardarActionPerformed
      // Validamos los datos        
      if (nombre.getText().isEmpty())
      {
          JOptionPane.showMessageDialog(this, "No se capturó el nombre del administrador",
                                              "Mensaje", JOptionPane.WARNING_MESSAGE);
          nombre.requestFocus();
          return;
      }    
      
      if (apellido.getText().isEmpty())
      {
          JOptionPane.showMessageDialog(this, "No se capturó el apellido del Administrador",
                                              "Mensaje", JOptionPane.WARNING_MESSAGE);
          apellido.requestFocus();
          return;
      }     
      
      if (login.getText().isEmpty())
      {
          JOptionPane.showMessageDialog(this, "No se capturó el login del Administrador",
                                              "Mensaje", JOptionPane.WARNING_MESSAGE);
          login.requestFocus();
          return;
      }   
      
      if (password.getText().isEmpty())
      {
          JOptionPane.showMessageDialog(this, "No se capturó el password del Administrador",
                                              "Mensaje", JOptionPane.WARNING_MESSAGE);
          password.requestFocus();
          return;
      }   
    
      Datos.Administrador oAdministrador = new Datos.Administrador(enlace);    
        
      // El ID lo genera automáticamente la base de datos cuando el registro es nuevo
      int idx;
      idx = (id.getText().isEmpty())?0:Integer.valueOf(id.getText());
      oAdministrador.setAdministrador(idx,
                                      nombre.getText(),
                                      apellido.getText(),
                                      telefono.getText(),
                                      login.getText(),
                                      password.getText(),
                                      email1.getText(),
                                      email2.getText(),
                                      (status.isSelected()?"A":"B"));

      
      if (this.accion.equals("NUEVO"))
      {
        // Se manda escribir a la base de datos
        if (!oAdministrador.Nuevo())
        {
          nombre.requestFocus();
          return;
        }       
      }
   
      if (this.accion.equals("EDITAR"))
      {
        // Se manda escribir a la base de datos
        if (!oAdministrador.Editar())
        {
          nombre.requestFocus();
          return;
        }
      }      
    
      if (this.accion.equals("ELIMINAR"))
      {
        // Se manda escribir a la base de datos
        if (!oAdministrador.Eliminar())
        {
          boton_guardar.requestFocus();
          return;
        }
      }
      padre.cargarTabla();
      this.dispose();      
    }//GEN-LAST:event_boton_guardarActionPerformed

    private void boton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_boton_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);                               
            }
        });
    }
    
    public void configurarPara(String accion)
    {
        this.accion = accion;
        if (accion.equals("NUEVO"))
        {            
           id.setEnabled(false);
           // Password aleatorio
           password.setText(password.getPassword().toString());
        }

        if (accion.equals("EDITAR"))
        {
            habilitarCampos(true);
            id.setEnabled(false);
        }
        
        if (accion.equals("ELIMINAR"))
        {
            habilitarCampos(false);            
        }
   }
    
   public void habilitarCampos(boolean estado)
   {
        id.setEditable(estado);
        nombre.setEditable(estado);    
        apellido.setEditable(estado);
        telefono.setEditable(estado);
        email1.setEditable(estado);
        email2.setEditable(estado);
        login.setEditable(estado);
        password.setEditable(estado);
        status.setEnabled(estado);
   }
    
   public void cargarCampos(int idx)
    {
        Datos.Administrador oAdministrador = new Datos.Administrador(enlace);
        oAdministrador.Buscar(idx);        
        id.setText(Integer.toString(oAdministrador.getID()));        
        nombre.setText(oAdministrador.getNombre());
        apellido.setText(oAdministrador.getApellido());
        telefono.setText(oAdministrador.getTelefono());
        email1.setText(oAdministrador.getEmail1());
        email2.setText(oAdministrador.getEmail2());
        login.setText(oAdministrador.getLogin());
        password.setText(oAdministrador.getPassword());
        status.setSelected(oAdministrador.getStatus().equals("A")?true:false);
   } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JButton boton_cancelar;
    private javax.swing.JButton boton_guardar;
    private javax.swing.JTextField email1;
    private javax.swing.JTextField email2;
    private javax.swing.JTextField id;
    private javax.swing.JLabel lapellido;
    private javax.swing.JLabel lcodigo;
    private javax.swing.JLabel ldescri;
    private javax.swing.JLabel lemail1;
    private javax.swing.JLabel lemail2;
    private javax.swing.JLabel llogin;
    private javax.swing.JTextField login;
    private javax.swing.JLabel lpassword;
    private javax.swing.JLabel ltelefono;
    private javax.swing.JTextField nombre;
    private javax.swing.JPasswordField password;
    private javax.swing.JCheckBox status;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
