/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Seguridad;

import javax.swing.JOptionPane;

/**
 *
 * @author Paul
 */
public class Login extends javax.swing.JDialog {   
    /**
     * Creates new form Login
     */
    public boolean cancelar=false;
    public Login() {
        initComponents(); 
        password.selectAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        llogin = new javax.swing.JLabel();
        lpassword = new javax.swing.JLabel();
        boton_guardar = new javax.swing.JButton();
        boton_cancelar = new javax.swing.JButton();
        login = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();

        setTitle("Identificación de administrador");
        setMinimumSize(new java.awt.Dimension(580, 200));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setPreferredSize(new java.awt.Dimension(580, 200));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        llogin.setText("Usuario");
        getContentPane().add(llogin);
        llogin.setBounds(30, 50, 120, 20);

        lpassword.setText("Contraseña");
        getContentPane().add(lpassword);
        lpassword.setBounds(300, 50, 110, 20);

        boton_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuardarTodo.png"))); // NOI18N
        boton_guardar.setMnemonic('G');
        boton_guardar.setText("OK");
        boton_guardar.setToolTipText("Guardar registro");
        boton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_guardar);
        boton_guardar.setBounds(250, 140, 130, 40);

        boton_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        boton_cancelar.setMnemonic('C');
        boton_cancelar.setText("Cancelar");
        boton_cancelar.setToolTipText("Cancelar actualización");
        boton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_cancelar);
        boton_cancelar.setBounds(390, 140, 130, 40);

        login.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        login.setMinimumSize(new java.awt.Dimension(8, 24));
        login.setPreferredSize(new java.awt.Dimension(8, 24));
        getContentPane().add(login);
        login.setBounds(30, 70, 190, 28);

        password.setText("jPasswordField1");
        getContentPane().add(password);
        password.setBounds(300, 70, 220, 28);

        setSize(new java.awt.Dimension(602, 249));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardarActionPerformed
      // Validamos los datos   
      if (login.getText().isEmpty())
      {
          JOptionPane.showMessageDialog(this, "No se capturó el login de administrador",
                                              "Mensaje", JOptionPane.WARNING_MESSAGE);
          login.requestFocus();
          return;
      }   
      
      if (password.getText().isEmpty())
      {
          JOptionPane.showMessageDialog(this, "No se capturó el password de administrador",
                                              "Mensaje", JOptionPane.WARNING_MESSAGE);
          password.requestFocus();
          return;
      }      
      
      // A partir de aquí vamos a establecer una conexión con el lógin y contraseña
      // El valor de devolución será true (exitoso) false (no autentificado)
      
      this.dispose();      
    }//GEN-LAST:event_boton_guardarActionPerformed

    private void boton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cancelarActionPerformed
        // TODO add your handling code here:
        cancelar = true;
        setVisible(false);
    }//GEN-LAST:event_boton_cancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cancelar = true;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);                               
            }
        });
    }
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_cancelar;
    private javax.swing.JButton boton_guardar;
    private javax.swing.JLabel llogin;
    public javax.swing.JTextField login;
    private javax.swing.JLabel lpassword;
    public javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
