/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Seguridad;

import Datos.Conexion;
import Datos.ListaEleccionSeguridad;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Paul
 */
public class Modulo extends javax.swing.JDialog {
    private String accion;
    public Conexion enlace;
    public Modulos padre;
    
    /**
     * Creates new form Modulo
     */
    public Modulo() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lcodigo = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        ldescri = new javax.swing.JLabel();
        boton_guardar = new javax.swing.JButton();
        boton_cancelar = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        lcomponente = new javax.swing.JLabel();
        componente = new javax.swing.JComboBox();
        modulo = new javax.swing.JFormattedTextField();
        sub = new javax.swing.JFormattedTextField();
        subsub = new javax.swing.JFormattedTextField();
        lmodulo = new javax.swing.JLabel();
        lsub = new javax.swing.JLabel();
        lsubsub = new javax.swing.JLabel();
        etiqueta = new javax.swing.JCheckBox();
        estado = new javax.swing.JCheckBox();
        tipo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Módulo");
        setMinimumSize(new java.awt.Dimension(580, 200));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setPreferredSize(new java.awt.Dimension(580, 200));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(null);

        lcodigo.setText("ID");
        getContentPane().add(lcodigo);
        lcodigo.setBounds(40, 30, 50, 14);

        nombre.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        nombre.setMinimumSize(new java.awt.Dimension(8, 24));
        nombre.setPreferredSize(new java.awt.Dimension(8, 24));
        getContentPane().add(nombre);
        nombre.setBounds(270, 50, 290, 28);

        ldescri.setText("Nombre");
        getContentPane().add(ldescri);
        ldescri.setBounds(270, 30, 220, 14);

        boton_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuardarTodo.png"))); // NOI18N
        boton_guardar.setMnemonic('G');
        boton_guardar.setText("OK");
        boton_guardar.setToolTipText("Guardar registro");
        boton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_guardar);
        boton_guardar.setBounds(280, 280, 130, 40);

        boton_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        boton_cancelar.setMnemonic('C');
        boton_cancelar.setText("Cancelar");
        boton_cancelar.setToolTipText("Cancelar actualización");
        boton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_cancelar);
        boton_cancelar.setBounds(420, 280, 130, 40);

        id.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        id.setEnabled(false);
        id.setMinimumSize(new java.awt.Dimension(8, 24));
        id.setPreferredSize(new java.awt.Dimension(8, 24));
        getContentPane().add(id);
        id.setBounds(40, 50, 50, 28);

        lcomponente.setText("Componente ");
        getContentPane().add(lcomponente);
        lcomponente.setBounds(40, 190, 120, 14);

        getContentPane().add(componente);
        componente.setBounds(40, 210, 400, 28);
        getContentPane().add(modulo);
        modulo.setBounds(100, 50, 40, 28);
        getContentPane().add(sub);
        sub.setBounds(150, 50, 40, 28);
        getContentPane().add(subsub);
        subsub.setBounds(200, 50, 40, 28);

        lmodulo.setText("Módulo");
        getContentPane().add(lmodulo);
        lmodulo.setBounds(100, 30, 50, 14);

        lsub.setText("Sub");
        getContentPane().add(lsub);
        lsub.setBounds(150, 30, 40, 14);

        lsubsub.setText("SubSub");
        getContentPane().add(lsubsub);
        lsubsub.setBounds(200, 30, 60, 14);

        etiqueta.setText("Etiqueta");
        getContentPane().add(etiqueta);
        etiqueta.setBounds(40, 130, 80, 28);

        estado.setText("Activo");
        getContentPane().add(estado);
        estado.setBounds(130, 130, 81, 28);

        tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Aplica", "Ventana", "Reporte" }));
        getContentPane().add(tipo);
        tipo.setBounds(280, 130, 160, 28);

        jLabel1.setText("Tipo de programa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 110, 110, 14);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-598)/2, (screenSize.height-391)/2, 598, 391);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardarActionPerformed
      // Validamos los datos        
      if (nombre.getText().isEmpty())
      {
          JOptionPane.showMessageDialog(this, "No se capturó el nombre de la Asignatura",
                                              "Mensaje", JOptionPane.WARNING_MESSAGE);
          nombre.requestFocus();
          return;
      }    
      
      if (componente.getSelectedIndex()==-1)
      {
          JOptionPane.showMessageDialog(this, "No seleccionó un componente para el módulo",
                                              "Mensaje", JOptionPane.WARNING_MESSAGE);
          nombre.requestFocus();
          return;
      }    
   
    
      Datos.Modulo oModulo = new Datos.Modulo(enlace);    
        
      // El ID lo genera automáticamente la base de datos cuando el registro es nuevo
      int idx;
      idx = (id.getText().isEmpty())?0:Integer.valueOf(id.getText());
      oModulo.setModulo(idx,
                        Integer.valueOf(modulo.getText()),
                        Integer.valueOf(sub.getText()),
                        Integer.valueOf(subsub.getText()),
                        nombre.getText(),
                        etiqueta.isSelected(),
                        estado.isSelected()?"A":"B",
                        tipo.getSelectedIndex(),
                        ((ListaEleccionSeguridad)componente.getSelectedItem()).componente); 
      
      if (this.accion.equals("NUEVO"))
      {
        // Se manda escribir a la base de datos
        if (!oModulo.Nuevo())
        {
          nombre.requestFocus();
          return;
        }
        else
        {
          padre.cargarTabla();
          nombre.requestFocus();
        }
      }
   
      if (this.accion.equals("EDITAR"))
      {
        // Se manda escribir a la base de datos
        if (!oModulo.Editar())
        {
          nombre.requestFocus();
          return;
        }
      }      
    
      if (this.accion.equals("ELIMINAR"))
      {
        // Se manda escribir a la base de datos
        if (!oModulo.Eliminar())
        {
          boton_guardar.requestFocus();
          return;
        }
      }
      padre.cargarTabla();
      this.dispose();      
    }//GEN-LAST:event_boton_guardarActionPerformed

    private void boton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_boton_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modulo().setVisible(true);                               
            }
        });
    }
    
    public void configurarPara(String accion)
    {
        this.accion = accion;
        if (accion.equals("NUEVO"))
        {            
           habilitarCampos(true); 
           //id.setEnabled(false);
        }

        if (accion.equals("EDITAR"))
        {
            habilitarCampos(true);
            //id.setEnabled(false);
        }
        
        if (accion.equals("ELIMINAR"))
        {
            habilitarCampos(false);            
        }
        
        // Cargamos los datos de la tabla de módulos a la lista
        /*Datos.Modulo oModulo = new Datos.Modulo(enlace);
        DefaultComboBoxModel datos_modulo = new DefaultComboBoxModel();
        datos_modulo.removeAllElements();
        Vector items_modulo = new Vector();
        items_modulo.addAll(oModulo.Lista());
        for (int i = 0; i < items_modulo.size(); i++)
        {
          datos_modulo.addElement(items_modulo.get(i));
        }
        componente.setModel(datos_modulo); */
        componente.setModel(new Permisos().getModelo());
    }
    
    public void habilitarCampos(boolean e)
    {
        modulo.setEditable(e);
        nombre.setEditable(e);
        etiqueta.setEnabled(e);
        estado.setEnabled(e);
        tipo.setEnabled(e);
        sub.setEditable(e);
        subsub.setEditable(e);
        componente.setEnabled(e);
   }
    
   public void cargarCampos(int idx)
    {
        Datos.Modulo oModulo = new Datos.Modulo(enlace);
        oModulo.Buscar(idx);
        id.setText(Integer.toString(oModulo.getID())); 
        modulo.setText(Integer.toString(oModulo.getModulo()));
        sub.setText(Integer.toString(oModulo.getSubModulo()));
        subsub.setText(Integer.toString(oModulo.getSubSubModulo()));
        nombre.setText(oModulo.getNombre());
        etiqueta.setSelected(oModulo.getEtiqueta());
        estado.setSelected(oModulo.getEstado().equals("A")?true:false);
        tipo.setSelectedIndex(oModulo.getTipo());             
        componente.setSelectedItem(new ListaEleccionSeguridad(0,"",oModulo.getComponente()));
   } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_cancelar;
    private javax.swing.JButton boton_guardar;
    private javax.swing.JComboBox componente;
    private javax.swing.JCheckBox estado;
    private javax.swing.JCheckBox etiqueta;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lcodigo;
    private javax.swing.JLabel lcomponente;
    private javax.swing.JLabel ldescri;
    private javax.swing.JLabel lmodulo;
    private javax.swing.JLabel lsub;
    private javax.swing.JLabel lsubsub;
    private javax.swing.JFormattedTextField modulo;
    private javax.swing.JTextField nombre;
    private javax.swing.JFormattedTextField sub;
    private javax.swing.JFormattedTextField subsub;
    private javax.swing.JComboBox tipo;
    // End of variables declaration//GEN-END:variables
}
