/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Catalogos;

import Datos.Conexion;
import Datos.ListaEleccion;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Paul
 */
public class Asignatura_Tema extends javax.swing.JFrame {
    private String accion;
    public Conexion enlace;
    public Asignaturas_Temas padre;
    private int id_carrera=0;
    private int id_asignatura=0;
    
    /**
     * Creates new form Asignatura_Tema
     */
    public Asignatura_Tema() {
        initComponents();        
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ltema = new javax.swing.JLabel();
        tema = new javax.swing.JFormattedTextField();
        lsub = new javax.swing.JLabel();
        sub = new javax.swing.JFormattedTextField();
        lsubsub = new javax.swing.JLabel();
        subsub = new javax.swing.JFormattedTextField();
        lnombre = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        lconaic_area = new javax.swing.JLabel();
        conaic_area = new javax.swing.JComboBox();
        legel_area = new javax.swing.JLabel();
        boton_guardar = new javax.swing.JButton();
        boton_cancelar = new javax.swing.JButton();
        egel_area = new javax.swing.JComboBox();
        lid = new javax.swing.JLabel();
        id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Temas de Asignatura");
        setMinimumSize(new java.awt.Dimension(580, 200));
        setName("asignatura_tema"); // NOI18N
        setPreferredSize(new java.awt.Dimension(580, 200));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(null);

        ltema.setText("Tema");
        getContentPane().add(ltema);
        ltema.setBounds(40, 20, 50, 14);
        getContentPane().add(tema);
        tema.setBounds(40, 40, 50, 28);

        lsub.setText("Sub");
        getContentPane().add(lsub);
        lsub.setBounds(110, 20, 50, 14);
        getContentPane().add(sub);
        sub.setBounds(100, 40, 50, 28);

        lsubsub.setText("SubSub");
        getContentPane().add(lsubsub);
        lsubsub.setBounds(160, 20, 60, 14);
        getContentPane().add(subsub);
        subsub.setBounds(160, 40, 50, 28);

        lnombre.setText("Nombre");
        getContentPane().add(lnombre);
        lnombre.setBounds(220, 20, 200, 14);

        nombre.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        nombre.setMinimumSize(new java.awt.Dimension(8, 24));
        nombre.setPreferredSize(new java.awt.Dimension(8, 24));
        getContentPane().add(nombre);
        nombre.setBounds(220, 40, 390, 28);

        lconaic_area.setText("Area de Conaic");
        getContentPane().add(lconaic_area);
        lconaic_area.setBounds(40, 90, 120, 14);

        getContentPane().add(conaic_area);
        conaic_area.setBounds(40, 110, 410, 28);

        legel_area.setText("Area de Egel");
        getContentPane().add(legel_area);
        legel_area.setBounds(40, 160, 120, 14);

        boton_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuardarTodo.png"))); // NOI18N
        boton_guardar.setMnemonic('G');
        boton_guardar.setText("OK");
        boton_guardar.setToolTipText("Guardar registro");
        boton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_guardar);
        boton_guardar.setBounds(330, 240, 130, 40);

        boton_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        boton_cancelar.setMnemonic('C');
        boton_cancelar.setText("Cancelar");
        boton_cancelar.setToolTipText("Cancelar actualización");
        boton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_cancelar);
        boton_cancelar.setBounds(470, 240, 130, 40);

        getContentPane().add(egel_area);
        egel_area.setBounds(40, 180, 410, 28);

        lid.setText("ID");
        getContentPane().add(lid);
        lid.setBounds(40, 230, 34, 14);

        id.setEnabled(false);
        getContentPane().add(id);
        id.setBounds(40, 250, 70, 28);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-657)/2, (screenSize.height-350)/2, 657, 350);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardarActionPerformed
      // Validamos los datos      
      if (nombre.getText().isEmpty())
      {
          JOptionPane.showMessageDialog(this, "No se capturó el nombre del tema, subtema o subsubtema",
                                              "Mensaje", JOptionPane.WARNING_MESSAGE);
          nombre.requestFocus();
          return;
      }            
    
      Datos.Asignatura_Tema oAsignatura_Tema = new Datos.Asignatura_Tema(enlace);    
        
      // El ID lo genera automáticamente la base de datos cuando el registro es nuevo
      int idx;
      idx = (id.getText().isEmpty())?0:Integer.valueOf(id.getText());
      oAsignatura_Tema.setAsignatura_Tema(0,
                                Integer.valueOf(tema.getText()),
                                Integer.valueOf(sub.getText()),
                                Integer.valueOf(subsub.getText()),
                                nombre.getText(),
                                id_asignatura,
                                ((ListaEleccion)conaic_area.getSelectedItem()).id,
                                ((ListaEleccion)egel_area.getSelectedItem()).id); 
      
      if (this.accion.equals("NUEVO"))
      {
        // Se manda escribir a la base de datos
        if (!oAsignatura_Tema.Nuevo())
        {
          nombre.requestFocus();
          return;
        }
        else
        {
          padre.cargarTabla();
          nombre.setText("");
          nombre.requestFocus();
        }
      }
   
      if (this.accion.equals("EDITAR"))
      {
        // Se manda escribir a la base de datos
        if (!oAsignatura_Tema.Editar())
        {
          nombre.requestFocus();
          return;
        }
      }      
    
      if (this.accion.equals("ELIMINAR"))
      {
        // Se manda escribir a la base de datos
        if (!oAsignatura_Tema.Eliminar())
        {
          boton_guardar.requestFocus();
          return;
        }
      }
      padre.cargarTabla();
      this.dispose();      
    }//GEN-LAST:event_boton_guardarActionPerformed

    private void boton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_boton_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Egel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asignatura_Tema().setVisible(true);                               
            }
        });
    }
    
    public void configurarPara(String accion)
    {
        this.accion = accion;
        if (accion.equals("NUEVO"))
        {            
           id.setEnabled(false);
        }

        if (accion.equals("EDITAR"))
        {
            habilitarCampos(true);
            id.setEnabled(false);
        }
        
        if (accion.equals("ELIMINAR"))
        {
            habilitarCampos(false);   
            id.setEnabled(false);
        }
        
        /*
        // Cargamos los datos de la tabla Institucion a la lista
        Datos.Institucion oInstitucion = new Datos.Institucion(enlace);
        DefaultComboBoxModel datos_institucion = new DefaultComboBoxModel();
        datos_institucion.removeAllElements();
        Vector items_institucion = new Vector();
        items_institucion.addAll(oInstitucion.Lista());
        for (int i = 0; i < items_institucion.size(); i++)
        {
          datos_institucion.addElement(items_institucion.get(i));
        }
        institucion.setModel(datos_institucion); 
         
        // Cargamos los datos de la tabla Carreras a la lista
        Datos.Carrera oCarrera = new Datos.Carrera(enlace);
        DefaultComboBoxModel datos_carrera = new DefaultComboBoxModel();
        datos_carrera.removeAllElements();
        Vector items_carrera = new Vector();
        items_carrera.addAll(oCarrera.Lista());
        for (int i = 0; i < items_carrera.size(); i++)
        {
          datos_carrera.addElement(items_carrera.get(i));
        }
        asignatura.setModel(datos_carrera);  
        
        // Cargamos los datos de la tabla Egel_Area a la lista
        Datos.Egel_Area oEgel_Area = new Datos.Egel_Area(enlace);
        DefaultComboBoxModel datos_egel_area = new DefaultComboBoxModel();
        datos_egel_area.removeAllElements();
        Vector items_egel_area = new Vector();
        // Solo nos traemos las áreas del Egel asignado a la carrera
        items_egel_area.addAll(oEgel_Area.Lista(((ListaEleccion)asignatura.getSelectedItem()).id));
        for (int i = 0; i < items_egel_area.size(); i++)
        {
          datos_egel_area.addElement(items_egel_area.get(i));
        }
        academia.setModel(datos_egel_area);*/
    }
    
    public void habilitarCampos(boolean estado)
    {
        id.setEnabled(false);
        tema.setEditable(estado);
        sub.setEditable(estado);
        subsub.setEditable(estado);
        nombre.setEditable(estado);    
        conaic_area.setEnabled(estado);
        egel_area.setEnabled(estado);
   }
    
   public void cargarCampos(int idx)
    {
        Datos.Asignatura_Tema oAsignatura_Tema = new Datos.Asignatura_Tema(enlace);
        oAsignatura_Tema.Buscar(idx);
        id.setText(Integer.toString(oAsignatura_Tema.getID()));  
        tema.setText(Integer.toString(oAsignatura_Tema.getTema()));
        sub.setText(Integer.toString(oAsignatura_Tema.getSubTema()));
        subsub.setText(Integer.toString(oAsignatura_Tema.getSubSubTema()));
        nombre.setText(oAsignatura_Tema.getNombre());        
        conaic_area.setSelectedItem(new ListaEleccion(oAsignatura_Tema.getConaicArea_id(),""));        
        egel_area.setSelectedItem(new ListaEleccion(oAsignatura_Tema.getEgelArea_id(),""));
        id_carrera = oAsignatura_Tema.getCarrera_id();
   } 
   
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_cancelar;
    private javax.swing.JButton boton_guardar;
    private javax.swing.JComboBox conaic_area;
    private javax.swing.JComboBox egel_area;
    private javax.swing.JTextField id;
    private javax.swing.JLabel lconaic_area;
    private javax.swing.JLabel legel_area;
    private javax.swing.JLabel lid;
    private javax.swing.JLabel lnombre;
    private javax.swing.JLabel lsub;
    private javax.swing.JLabel lsubsub;
    private javax.swing.JLabel ltema;
    private javax.swing.JTextField nombre;
    private javax.swing.JFormattedTextField sub;
    private javax.swing.JFormattedTextField subsub;
    private javax.swing.JFormattedTextField tema;
    // End of variables declaration//GEN-END:variables
}
