/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Catalogos;


import Datos.Conexion;
import Utilerias.ModeloTabla;
import eva.MDIApplication;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Paul Benitez
 */
public final class Asignaturas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Asignaturas
     */

    // Variables de la clase
    Conexion database;
    ResultSet registros;
    boolean filtrar=false; 
    Catalogos.Asignatura dlg;
    Catalogos.Asignaturas_Temas dlgTemas;

    public Asignaturas() {
        initComponents();
        // Conectar a la BD
        database = MDIApplication.database;
        //database = new Conexion();
        //database.conectar();
        int sizeFont = tabla.getFont().getSize()+4;
        tabla.setRowHeight((tabla.getRowHeight() * 2)+sizeFont);      
        tabla.setDefaultRenderer(Object.class, new Utilerias.MultiLineCellRenderer());
        cargarTabla();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JToolBar();
        BotonNuevo = new javax.swing.JButton();
        BotonEditar = new javax.swing.JButton();
        BotonBaja = new javax.swing.JButton();
        BotonReporte = new javax.swing.JButton();
        temas = new javax.swing.JButton();
        cuerpo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        pie = new javax.swing.JPanel();
        btn_Buscar = new javax.swing.JButton();
        campo = new javax.swing.JComboBox();
        CajaBusqueda = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Asignaturas");
        setMinimumSize(new java.awt.Dimension(820, 400));
        setName("asignaturas"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 600));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        menu.setFloatable(false);
        menu.setRollover(true);

        BotonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevo.png"))); // NOI18N
        BotonNuevo.setToolTipText("Nueva");
        BotonNuevo.setFocusable(false);
        BotonNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevoActionPerformed(evt);
            }
        });
        menu.add(BotonNuevo);

        BotonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Editar.png"))); // NOI18N
        BotonEditar.setToolTipText("Editar ");
        BotonEditar.setFocusable(false);
        BotonEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditarActionPerformed(evt);
            }
        });
        menu.add(BotonEditar);

        BotonBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Baja.png"))); // NOI18N
        BotonBaja.setToolTipText("Eliminar");
        BotonBaja.setFocusable(false);
        BotonBaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonBaja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBajaActionPerformed(evt);
            }
        });
        menu.add(BotonBaja);

        BotonReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Print.png"))); // NOI18N
        BotonReporte.setToolTipText("Imprimir ");
        BotonReporte.setFocusable(false);
        BotonReporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonReporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReporteActionPerformed(evt);
            }
        });
        menu.add(BotonReporte);

        temas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listas.png"))); // NOI18N
        temas.setToolTipText("Temas de la asignatura");
        temas.setFocusable(false);
        temas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        temas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        temas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temasActionPerformed(evt);
            }
        });
        menu.add(temas);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);

        tabla.setAutoCreateRowSorter(true);
        tabla.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setNextFocusableComponent(campo);
        tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        tabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaKeyReleased(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout cuerpoLayout = new javax.swing.GroupLayout(cuerpo);
        cuerpo.setLayout(cuerpoLayout);
        cuerpoLayout.setHorizontalGroup(
            cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
        );
        cuerpoLayout.setVerticalGroup(
            cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        pie.setPreferredSize(new java.awt.Dimension(442, 100));

        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        btn_Buscar.setToolTipText("Buscar");
        btn_Buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Buscar.setNextFocusableComponent(campo);
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        campo.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        campo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Nombre", "Academia", "Carrera", "Institución" }));

        CajaBusqueda.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        CajaBusqueda.setNextFocusableComponent(btn_Buscar);

        javax.swing.GroupLayout pieLayout = new javax.swing.GroupLayout(pie);
        pie.setLayout(pieLayout);
        pieLayout.setHorizontalGroup(
            pieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pieLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CajaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pieLayout.setVerticalGroup(
            pieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CajaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pie, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
            .addComponent(menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-900)/2, (screenSize.height-600)/2, 900, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevoActionPerformed
        // Aquí vamos a capturar una nueva        
        dlg = new Catalogos.Asignatura();
        dlg.enlace=database;
        dlg.configurarPara("NUEVO");
        dlg.setTitle("Nueva Asignatura");
        dlg.padre = this;    
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);               
    }//GEN-LAST:event_BotonNuevoActionPerformed

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        // Busqueda por patron de caracteres.
         if (CajaBusqueda.getText().isEmpty())
           filtrar = false;
         else
           filtrar = true;
         cargarTabla();
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void BotonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBajaActionPerformed
        // Primeramente vemos si está seleccionado un registro
        int registroActivo;
        registroActivo = tabla.getSelectedRow();

        if (registroActivo == -1)
        {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ninguna Asignatura",
                                          "Mensaje", JOptionPane.WARNING_MESSAGE);
            return;
        }       
        
        dlg = new Asignatura();
        dlg.enlace=database;
        dlg.configurarPara("ELIMINAR");
        dlg.setTitle("Eliminar Asignatura");
        dlg.padre = this;
        
        int idx;     
        idx = tabla.convertRowIndexToModel(registroActivo);
        idx = (int)((ModeloTabla)tabla.getModel()).getValueAt(idx, 0);
        //idx = (int)((ModeloTabla)tabla.getModel()).getValueAt(registroActivo, 0);
        dlg.cargarCampos(idx);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);          
    }//GEN-LAST:event_BotonBajaActionPerformed

    private void BotonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarActionPerformed
        // Primeramente vemos si está seleccionado un registro
        int registroActivo = tabla.getSelectedRow();
        if (registroActivo == -1)
        {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ninguna Asignatura",
                                          "Mensaje", JOptionPane.WARNING_MESSAGE);
            return;
        }        

        // Aquí vamos a editar el registro seleccionado
        dlg = new Asignatura();
        dlg.enlace=database;
        dlg.configurarPara("EDITAR");        
        dlg.setTitle("Actualizar Asignatura");
        dlg.padre = this;        
        int idx;   
        idx = tabla.convertRowIndexToModel(registroActivo);
        idx = (int)((ModeloTabla)tabla.getModel()).getValueAt(idx, 0);
        //idx = (int)((ModeloTabla)tabla.getModel()).getValueAt(registroActivo, 0);
        dlg.cargarCampos(idx);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);        
    }//GEN-LAST:event_BotonEditarActionPerformed

    private void BotonReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReporteActionPerformed
        
    }//GEN-LAST:event_BotonReporteActionPerformed

    private void temasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temasActionPerformed
        // Primeramente vemos si está seleccionado un registro
        int registroActivo = tabla.getSelectedRow();
        if (registroActivo == -1)
        {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ninguna Asignatura",
                                          "Mensaje", JOptionPane.WARNING_MESSAGE);
            return;
        }      
        
        // Obtenemos el id de la asignatura
        int idx;
        registroActivo = tabla.getSelectedRow();
        idx = tabla.convertRowIndexToModel(registroActivo);
        
        // Cerramos la ventana de los temas si ya estaba abierta
        if (dlgTemas != null)
        {
           dlgTemas.dispose();
           dlgTemas = null;
        }
        
        // Ahora tenemos que traer solamente los temas de la asignatura (forzamos filtro)
        int materia = (int)((ModeloTabla)tabla.getModel()).getValueAt(idx, 0);
        dlgTemas = new Asignaturas_Temas(materia);
        
        // Se agrega la ventana al escritorio
        MDIApplication.escritorio.add(dlgTemas);      
        // dlgTemas.toFront();
        // Se ubica la ventana en cascada
        dlgTemas.setLocation(MDIApplication.escritorio.getAllFrames().length*20, MDIApplication.escritorio.getAllFrames().length*20);
        /* dlgTemas.repaint();
        try {
            dlgTemas.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MDIApplication.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        dlgTemas.setVisible(true); 
        MDIApplication.alignWindowsActionPerformed(evt);
    }//GEN-LAST:event_temasActionPerformed

    private void tablaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyReleased
        int code = evt.getKeyCode();
        if (code == KeyEvent.VK_DOWN) 
        {
           // Nuevo filtro 
           RefreshTemas();
        }
        if (code == KeyEvent.VK_UP) 
        {
           // Nuevo filtro 
           RefreshTemas();
        }
    }//GEN-LAST:event_tablaKeyReleased

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // Esta es la forma de detectar doble clic
        if (evt.getClickCount() == 1 || evt.getClickCount() == 2) {
           RefreshTemas();
        }
    }//GEN-LAST:event_tablaMouseClicked

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        if (dlgTemas != null)
        {
           dlgTemas.dispose();
        }
    }//GEN-LAST:event_formInternalFrameClosed

    private void tablaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyPressed
        int code = evt.getKeyCode();
        if (code == KeyEvent.VK_ENTER) 
        { 
           evt.consume();
           RefreshTemas();
        }
    }//GEN-LAST:event_tablaKeyPressed

    public void RefreshTemas()
    {
       // La ventana de los temas esta cerrada / no filtrar 
       if (dlgTemas == null)
       {
           return;
       }
       // Nuevo filtro           
       int idx;
       int registroActivo = tabla.getSelectedRow();
       idx = tabla.convertRowIndexToModel(registroActivo); 
       int materia = (int)((ModeloTabla)tabla.getModel()).getValueAt(idx, 0);
       dlgTemas.RefreshTemas(materia);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Egels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {                 
                    new Asignaturas().setVisible(true);                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBaja;
    private javax.swing.JButton BotonEditar;
    private javax.swing.JButton BotonNuevo;
    private javax.swing.JButton BotonReporte;
    private javax.swing.JTextField CajaBusqueda;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JComboBox campo;
    private javax.swing.JPanel cuerpo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar menu;
    private javax.swing.JPanel pie;
    private javax.swing.JTable tabla;
    private javax.swing.JButton temas;
    // End of variables declaration//GEN-END:variables

    public void cargarTabla()
    {
       // Ejecutar metodo para recuperar los registros de la tabla de Asignatura
      Datos.Asignatura oAsignatura = new Datos.Asignatura(database);
      
      try {          
          if (filtrar) 
          {
            // Validamos en campo de id              
            if (campo.getSelectedIndex()==0)
            {
                try
                {
                   Integer.parseInt(CajaBusqueda.getText());
                }
                catch (NumberFormatException error)
                {
                   JOptionPane.showMessageDialog(this, "Patrón de búsqueda incorrecto, se esperaban números", "Error", JOptionPane.ERROR_MESSAGE);
                   filtrar = false;
                   CajaBusqueda.setText(""); btn_Buscar.doClick();
                   return;     
                }                             
            }            
            registros = oAsignatura.DataSetAsignatura(CajaBusqueda.getText(), campo.getSelectedIndex()); 
          }  
          else
          {
            registros = oAsignatura.DataSetAsignatura();
          }
      } catch (SQLException ex) {
          Logger.getLogger(Asignaturas.class.getName()).log(Level.SEVERE, null, ex);
      }
       
      // Se crea una manejador para los datos que van a recuperarse
      ModeloTabla modelo = new ModeloTabla();   
      modelo.rs = registros;
 
      try 
        {
         modelo.rsmd=registros.getMetaData();
        } 
      catch (SQLException ex) 
        {
         Logger.getLogger(Egels.class.getName()).log(Level.SEVERE, null, ex);
        }
      
      tabla.setModel(modelo);  
      tabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
      tabla.getColumnModel().getColumn(0).setPreferredWidth(70);      
      tabla.getColumnModel().getColumn(1).setPreferredWidth(300);
      tabla.getColumnModel().getColumn(2).setPreferredWidth(300);
      tabla.getColumnModel().getColumn(3).setPreferredWidth(300);
      tabla.getColumnModel().getColumn(4).setPreferredWidth(300);
    }}// Fin de la clase

