/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Catalogos;

import Datos.Conexion;
import Datos.ListaEleccion;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Paul
 */
public class Carrera extends javax.swing.JDialog {
    private String accion;
    public Conexion enlace;
    public Carreras padre;
    
    /**
     * Creates new form Carrera
     */
    public Carrera() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lcodigo = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        ldescri = new javax.swing.JLabel();
        boton_guardar = new javax.swing.JButton();
        boton_cancelar = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        legel = new javax.swing.JLabel();
        egel = new javax.swing.JComboBox();
        linstitucion = new javax.swing.JLabel();
        institucion = new javax.swing.JComboBox();
        lcontacto = new javax.swing.JLabel();
        contacto = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Egel");
        setMinimumSize(new java.awt.Dimension(580, 200));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setPreferredSize(new java.awt.Dimension(580, 200));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        lcodigo.setText("ID");
        getContentPane().add(lcodigo);
        lcodigo.setBounds(40, 100, 80, 14);

        nombre.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        nombre.setMinimumSize(new java.awt.Dimension(8, 24));
        nombre.setPreferredSize(new java.awt.Dimension(8, 24));
        getContentPane().add(nombre);
        nombre.setBounds(140, 130, 400, 28);

        ldescri.setText("Nombre de la carrera");
        getContentPane().add(ldescri);
        ldescri.setBounds(140, 100, 210, 14);

        boton_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuardarTodo.png"))); // NOI18N
        boton_guardar.setMnemonic('G');
        boton_guardar.setText("OK");
        boton_guardar.setToolTipText("Guardar registro");
        boton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_guardar);
        boton_guardar.setBounds(260, 350, 130, 40);

        boton_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        boton_cancelar.setMnemonic('C');
        boton_cancelar.setText("Cancelar");
        boton_cancelar.setToolTipText("Cancelar actualización");
        boton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_cancelar);
        boton_cancelar.setBounds(400, 350, 130, 40);

        id.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        id.setMinimumSize(new java.awt.Dimension(8, 24));
        id.setPreferredSize(new java.awt.Dimension(8, 24));
        getContentPane().add(id);
        id.setBounds(40, 130, 80, 28);

        legel.setText("Egel");
        getContentPane().add(legel);
        legel.setBounds(40, 180, 80, 14);

        getContentPane().add(egel);
        egel.setBounds(40, 210, 310, 28);

        linstitucion.setText("Institución");
        getContentPane().add(linstitucion);
        linstitucion.setBounds(40, 30, 100, 14);

        getContentPane().add(institucion);
        institucion.setBounds(40, 60, 500, 28);

        lcontacto.setText("Contacto");
        getContentPane().add(lcontacto);
        lcontacto.setBounds(40, 260, 90, 14);

        getContentPane().add(contacto);
        contacto.setBounds(40, 290, 490, 28);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-602)/2, (screenSize.height-472)/2, 602, 472);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardarActionPerformed
      // Validamos los datos
      if (nombre.getText().isEmpty())
      {
          JOptionPane.showMessageDialog(this, "No se capturó el nombre de la Carrera",
                                          "Mensaje", JOptionPane.WARNING_MESSAGE);
          nombre.requestFocus();
          return;
      }           
    
      Datos.Carrera oCarrera = new Datos.Carrera(enlace);    
        
      // El ID lo genera automáticamente la base de datos cuando el registro es nuevo
      int idx;
      idx = (id.getText().isEmpty())?0:Integer.valueOf(id.getText());
      oCarrera.setCarrera(idx,
                          nombre.getText(),
                          ((ListaEleccion)egel.getSelectedItem()).getId(),
                          ((ListaEleccion)contacto.getSelectedItem()).getId(),
                          ((ListaEleccion)institucion.getSelectedItem()).getId()); 
      
      if (this.accion.equals("NUEVO"))
      {
        // Se manda escribir a la base de datos
        if (!oCarrera.Nuevo())
        {
          nombre.requestFocus();
          return;
        }
      }
   
      if (this.accion.equals("EDITAR"))
      {
        // Se manda escribir a la base de datos
        if (!oCarrera.Editar())
        {
          nombre.requestFocus();
          return;
        }
      }      
    
      if (this.accion.equals("ELIMINAR"))
      {
        // Se manda escribir a la base de datos
        if (!oCarrera.Eliminar())
        {
          boton_guardar.requestFocus();
          return;
        }
      }
      
      this.dispose();
      padre.cargarTabla();
    }//GEN-LAST:event_boton_guardarActionPerformed

    private void boton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_boton_cancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Egel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carrera().setVisible(true);                               
            }
        });
    }
    
    public void configurarPara(String accion)
    {
        this.accion = accion;
        if (accion.equals("NUEVO"))
        {            
           id.setEnabled(false);
        }

        if (accion.equals("EDITAR"))
        {
            habilitarCampos(true);
            id.setEnabled(false);
        }
        
        if (accion.equals("ELIMINAR"))
        {
            habilitarCampos(false);            
        }
         
        // Cargamos los datos de las instituciones
        Datos.Institucion oInstitucion = new Datos.Institucion(enlace);
        DefaultComboBoxModel datos_institucion = new DefaultComboBoxModel();
        datos_institucion.removeAllElements();
        Vector items_institucion = new Vector();
        items_institucion.addAll(oInstitucion.Lista());
        for (int i = 0; i < items_institucion.size(); i++)
        {
          datos_institucion.addElement(items_institucion.get(i));
        }
        institucion.setModel(datos_institucion);        
        
        // Cargamos los datos de los egels
        Datos.Egel oEgel = new Datos.Egel(enlace);
        DefaultComboBoxModel datos_egel = new DefaultComboBoxModel();
        datos_egel.removeAllElements();
        Vector items_egel = new Vector();
        items_egel.addAll(oEgel.Lista());
        for (int i = 0; i < items_egel.size(); i++)
        {
          datos_egel.addElement(items_egel.get(i));
        }
        egel.setModel(datos_egel);   
        
        // Cargamos los datos de los contactos
        Datos.Contacto oContacto = new Datos.Contacto(enlace);
        DefaultComboBoxModel datos_contacto = new DefaultComboBoxModel();
        datos_contacto.removeAllElements();
        Vector items_contacto = new Vector();
        items_contacto.addAll(oContacto.Lista());
        for (int i = 0; i < items_contacto.size(); i++)
        {
          datos_contacto.addElement(items_contacto.get(i));
        }
        contacto.setModel(datos_contacto); 
    }
    
    public void habilitarCampos(boolean estado)
    {
        institucion.setEnabled(estado);
        id.setEditable(estado);
        nombre.setEditable(estado);      
        egel.setEnabled(estado);
        contacto.setEnabled(estado);
   }
    
   public void cargarCampos(int idx)
    {
        Datos.Carrera oCarrera = new Datos.Carrera(enlace);
        oCarrera.Buscar(idx);  
        institucion.setSelectedItem(new ListaEleccion(oCarrera.getInstitucion_id(),""));
        id.setText(Integer.toString(oCarrera.getID())); 
        nombre.setText(oCarrera.getNombre());
        egel.setSelectedItem(new ListaEleccion(oCarrera.getEgel_id(),""));     
        contacto.setSelectedItem(new ListaEleccion(oCarrera.getContacto_id(),""));
   } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_cancelar;
    private javax.swing.JButton boton_guardar;
    private javax.swing.JComboBox contacto;
    private javax.swing.JComboBox egel;
    private javax.swing.JTextField id;
    private javax.swing.JComboBox institucion;
    private javax.swing.JLabel lcodigo;
    private javax.swing.JLabel lcontacto;
    private javax.swing.JLabel ldescri;
    private javax.swing.JLabel legel;
    private javax.swing.JLabel linstitucion;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
