/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Catalogos;


import Datos.Conexion;
import Utilerias.ModeloTabla;
import eva.MDIApplication;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Paul Benitez
 */
public final class Egels extends javax.swing.JInternalFrame {

    /**
     * Creates new form Institucions
     */

    // Variables de la clase
    Conexion database;
    ResultSet registros;
    boolean filtrar=false; 
    Catalogos.Egel dlg;
    Catalogos.Egel_Areas dlgAreas;

    public Egels() {
        initComponents();
        // Conectar a la BD
        database = MDIApplication.database;
        //database = new Conexion();
        //database.conectar();
        cargarTabla();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JToolBar();
        BotonNuevo = new javax.swing.JButton();
        BotonEditar = new javax.swing.JButton();
        BotonBaja = new javax.swing.JButton();
        BotonReporte = new javax.swing.JButton();
        BotonEgel = new javax.swing.JButton();
        cuerpo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        pie = new javax.swing.JPanel();
        btn_Buscar = new javax.swing.JButton();
        CajaBusqueda = new javax.swing.JTextField();
        campo = new javax.swing.JComboBox();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Tipos de Egel");
        setMinimumSize(new java.awt.Dimension(820, 400));
        setName("Lineas"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 600));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        menu.setRollover(true);

        BotonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevo.png"))); // NOI18N
        BotonNuevo.setToolTipText("Nuevo");
        BotonNuevo.setFocusable(false);
        BotonNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevoActionPerformed(evt);
            }
        });
        menu.add(BotonNuevo);

        BotonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Editar.png"))); // NOI18N
        BotonEditar.setToolTipText("Editar");
        BotonEditar.setFocusable(false);
        BotonEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditarActionPerformed(evt);
            }
        });
        menu.add(BotonEditar);

        BotonBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Baja.png"))); // NOI18N
        BotonBaja.setToolTipText("Eliminar");
        BotonBaja.setFocusable(false);
        BotonBaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonBaja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBajaActionPerformed(evt);
            }
        });
        menu.add(BotonBaja);

        BotonReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Print.png"))); // NOI18N
        BotonReporte.setToolTipText("Imprimir ");
        BotonReporte.setFocusable(false);
        BotonReporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonReporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReporteActionPerformed(evt);
            }
        });
        menu.add(BotonReporte);

        BotonEgel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/egel.png"))); // NOI18N
        BotonEgel.setFocusable(false);
        BotonEgel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonEgel.setMaximumSize(new java.awt.Dimension(39, 39));
        BotonEgel.setMinimumSize(new java.awt.Dimension(39, 39));
        BotonEgel.setPreferredSize(new java.awt.Dimension(39, 39));
        BotonEgel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonEgel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEgelActionPerformed(evt);
            }
        });
        menu.add(BotonEgel);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);

        tabla.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setNextFocusableComponent(campo);
        tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        tabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaKeyReleased(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout cuerpoLayout = new javax.swing.GroupLayout(cuerpo);
        cuerpo.setLayout(cuerpoLayout);
        cuerpoLayout.setHorizontalGroup(
            cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
        );
        cuerpoLayout.setVerticalGroup(
            cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );

        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        btn_Buscar.setToolTipText("Buscar");
        btn_Buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Buscar.setNextFocusableComponent(campo);
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        CajaBusqueda.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        CajaBusqueda.setNextFocusableComponent(btn_Buscar);

        campo.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        campo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Nombre" }));

        javax.swing.GroupLayout pieLayout = new javax.swing.GroupLayout(pie);
        pie.setLayout(pieLayout);
        pieLayout.setHorizontalGroup(
            pieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CajaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pieLayout.setVerticalGroup(
            pieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CajaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setBounds(0, 0, 900, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevoActionPerformed
        // Aquí vamos a capturr uno nuevo
        dlg = new Catalogos.Egel();
        dlg.configurarPara("NUEVO");
        dlg.enlace=database;
        dlg.setTitle("Nuevo Egel");
        dlg.padre = this;    
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);               
    }//GEN-LAST:event_BotonNuevoActionPerformed

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        // Busqueda por patron de caracteres.
         if (CajaBusqueda.getText().isEmpty())
           filtrar = false;
         else
           filtrar = true;
         cargarTabla();
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void BotonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBajaActionPerformed
        // Primeramente vemos si está seleccionado un registro
        int registroActivo;
        registroActivo = tabla.getSelectedRow();

        if (registroActivo == -1)
        {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún Egel",
                                          "Mensaje", JOptionPane.WARNING_MESSAGE);
        }       
        
        dlg = new Egel();
        dlg.configurarPara("ELIMINAR");
        dlg.enlace=database;
        dlg.setTitle("Eliminar Egel");
        dlg.padre = this;
        
        int idx; 
        idx = tabla.convertRowIndexToModel(registroActivo);
        idx = (int)((ModeloTabla)tabla.getModel()).getValueAt(idx, 0);
        //idx = (int)((ModeloTabla)tabla.getModel()).getValueAt(registroActivo, 0);
        dlg.cargarCampos(idx);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);        
    }//GEN-LAST:event_BotonBajaActionPerformed

    private void BotonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarActionPerformed
        // Primeramente vemos si está seleccionado un registro
        int registroActivo = tabla.getSelectedRow();

        if (registroActivo == -1)
        {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún Egel",
                                          "Mensaje", JOptionPane.WARNING_MESSAGE);
        }        
         
        // Aquí vamos a editar el registro seleccionado
        dlg = new Egel();
        dlg.configurarPara("EDITAR");
        dlg.enlace=database;
        dlg.setTitle("Actualizar Egel");
        dlg.padre = this;
        
        int idx;  
        idx = tabla.convertRowIndexToModel(registroActivo);
        idx = (int)((ModeloTabla)tabla.getModel()).getValueAt(idx, 0);
        //idx = (int)((ModeloTabla)tabla.getModel()).getValueAt(registroActivo, 0);
        dlg.cargarCampos(idx);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);
    }//GEN-LAST:event_BotonEditarActionPerformed

    private void BotonReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReporteActionPerformed
        
    }//GEN-LAST:event_BotonReporteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    }//GEN-LAST:event_formWindowClosing

    private void BotonEgelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEgelActionPerformed
        // Primeramente vemos si está seleccionado un registro
        int registroActivo = tabla.getSelectedRow();
        if (registroActivo == -1)
        {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún Egel",
                                          "Mensaje", JOptionPane.WARNING_MESSAGE);
            return;
        }      
        
        // Obtenemos el id de la asignatura
        int idx;
        registroActivo = tabla.getSelectedRow();
        idx = tabla.convertRowIndexToModel(registroActivo);
        
        // Cerramos la ventana de los temas si ya estaba abierta
        if (dlgAreas != null)
        {
           dlgAreas.dispose();
           dlgAreas = null;
        }
        
        // Ahora tenemos que traer solamente los temas del egel (forzamos filtro)
        int egel = (int)((ModeloTabla)tabla.getModel()).getValueAt(idx, 0);
        dlgAreas = new Egel_Areas(egel);
        // Se agrega la ventana al escritorio
        MDIApplication.escritorio.add(dlgAreas); 
        // Establecemos ubicación de la ventana
        dlgAreas.setLocation(MDIApplication.escritorio.getAllFrames().length*20, MDIApplication.escritorio.getAllFrames().length*20);
        // Rotulamos la ventana del área de Egel
        dlgAreas.setTitle("Areas de conocimiento del "+
                          ((ModeloTabla)tabla.getModel()).getValueAt(idx, 1));
        dlgAreas.setVisible(true); 
        // Alineamos las dos ventanas
        MDIApplication.alignWindowsActionPerformed(evt);
    }//GEN-LAST:event_BotonEgelActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
         // Esta es la forma de detectar doble clic
        if (evt.getClickCount() == 1 || evt.getClickCount() == 2) {
           RefreshTemas();
        }
    }//GEN-LAST:event_tablaMouseClicked

    private void tablaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyPressed
        int code = evt.getKeyCode();
        if (code == KeyEvent.VK_ENTER) 
        { 
           evt.consume();
           RefreshTemas();
        }
    }//GEN-LAST:event_tablaKeyPressed

    private void tablaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyReleased
        int code = evt.getKeyCode();
        if (code == KeyEvent.VK_DOWN) 
        {
           // Nuevo filtro 
           RefreshTemas();
        }
        if (code == KeyEvent.VK_UP) 
        {
           // Nuevo filtro 
           RefreshTemas();
        }
    }//GEN-LAST:event_tablaKeyReleased

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        if (dlgAreas != null)
        {
           dlgAreas.dispose();
        }
    }//GEN-LAST:event_formInternalFrameClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Egels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {                 
                    new Egels().setVisible(true);                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBaja;
    private javax.swing.JButton BotonEditar;
    private javax.swing.JButton BotonEgel;
    private javax.swing.JButton BotonNuevo;
    private javax.swing.JButton BotonReporte;
    private javax.swing.JTextField CajaBusqueda;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JComboBox campo;
    private javax.swing.JPanel cuerpo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar menu;
    private javax.swing.JPanel pie;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

    public void cargarTabla()
    {
       // Ejecutar metodo para recuperar los registros de la tabla de Institucion
      Datos.Egel oEgel = new Datos.Egel(database);
      
      try {
          
          if (filtrar) 
          {
            // Validamos en campo de id              
            if (campo.getSelectedIndex()==0)
            {
                try
                {
                   Integer.parseInt(CajaBusqueda.getText());
                }
                catch (NumberFormatException error)
                {
                   JOptionPane.showMessageDialog(this, "Patrón de búsqueda incorrecto, se esperaban números", "Error", JOptionPane.ERROR_MESSAGE);
                   filtrar = false;
                   CajaBusqueda.setText(""); btn_Buscar.doClick();
                   return;     
                }                             
            }            
            registros = oEgel.DataSetEgel(CajaBusqueda.getText(), campo.getSelectedIndex()); 
          }  
          else
          {
            registros = oEgel.DataSetEgel();
          }
      } catch (SQLException ex) {
          Logger.getLogger(Egels.class.getName()).log(Level.SEVERE, null, ex);
      }
       
      // Se crea una manejador para los datos que van a recuperarse
      ModeloTabla modelo = new ModeloTabla();   
      modelo.rs = registros;
 
      try 
        {
         modelo.rsmd=registros.getMetaData();
        } 
      catch (SQLException ex) 
        {
         Logger.getLogger(Egels.class.getName()).log(Level.SEVERE, null, ex);
        }
      
      tabla.setModel(modelo);  
      tabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
      tabla.getColumnModel().getColumn(0).setPreferredWidth(70);      
      tabla.getColumnModel().getColumn(1).setPreferredWidth(400);
    }
    
    public void RefreshTemas()
    {
       // La ventana de los temas esta cerrada / no filtrar 
       if (dlgAreas == null)
       {
           return;
       }
       // Nuevo filtro           
       int idx;
       int registroActivo = tabla.getSelectedRow();
       idx = tabla.convertRowIndexToModel(registroActivo); 
       int egel = (int)((ModeloTabla)tabla.getModel()).getValueAt(idx, 0);
       // Rotulamos la ventana del área de Egel
       dlgAreas.setTitle("Areas de conocimiento del "+
                         ((ModeloTabla)tabla.getModel()).getValueAt(idx, 1));
       dlgAreas.RefreshTemas(egel);
    }
}// Fin de la clase

