/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Catalogos;

import Datos.Conexion;
import Datos.ListaEleccion;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Paul
 */
public class Instrumento extends javax.swing.JDialog {
    private String accion;
    public Conexion enlace;
    public Instrumentos padre;
    
    /**
     * Creates new form Linea
     */
    public Instrumento() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lcodigo = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        ldescri = new javax.swing.JLabel();
        boton_guardar = new javax.swing.JButton();
        boton_cancelar = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        numero_reactivos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dificultad = new javax.swing.JComboBox();
        legel = new javax.swing.JLabel();
        egel = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Egel");
        setMinimumSize(new java.awt.Dimension(580, 200));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setPreferredSize(new java.awt.Dimension(580, 200));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(null);

        lcodigo.setText("ID");
        getContentPane().add(lcodigo);
        lcodigo.setBounds(40, 110, 120, 14);

        nombre.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        nombre.setMinimumSize(new java.awt.Dimension(8, 24));
        nombre.setPreferredSize(new java.awt.Dimension(8, 24));
        getContentPane().add(nombre);
        nombre.setBounds(230, 130, 310, 28);

        ldescri.setText("Nombre");
        getContentPane().add(ldescri);
        ldescri.setBounds(230, 110, 310, 14);

        boton_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuardarTodo.png"))); // NOI18N
        boton_guardar.setMnemonic('G');
        boton_guardar.setText("OK");
        boton_guardar.setToolTipText("Guardar registro");
        boton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_guardar);
        boton_guardar.setBounds(260, 270, 130, 40);

        boton_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        boton_cancelar.setMnemonic('C');
        boton_cancelar.setText("Cancelar");
        boton_cancelar.setToolTipText("Cancelar actualización");
        boton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_cancelar);
        boton_cancelar.setBounds(400, 270, 130, 40);

        id.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        id.setMinimumSize(new java.awt.Dimension(8, 24));
        id.setPreferredSize(new java.awt.Dimension(8, 24));
        getContentPane().add(id);
        id.setBounds(40, 130, 120, 28);

        jLabel1.setText("Número de Reactivos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 190, 180, 14);

        numero_reactivos.setEditable(false);
        numero_reactivos.setEnabled(false);
        numero_reactivos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numero_reactivosKeyTyped(evt);
            }
        });
        getContentPane().add(numero_reactivos);
        numero_reactivos.setBounds(40, 220, 90, 28);

        jLabel2.setText("Dificultad");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 190, 90, 14);

        dificultad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nivel 1", "Nivel 2", "Nivel 3", "Nivel 4", "Nivel 5" }));
        getContentPane().add(dificultad);
        dificultad.setBounds(230, 220, 310, 28);

        legel.setText("Egel");
        getContentPane().add(legel);
        legel.setBounds(40, 30, 51, 14);

        getContentPane().add(egel);
        egel.setBounds(40, 60, 500, 28);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-602)/2, (screenSize.height-385)/2, 602, 385);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardarActionPerformed
      // Validamos los datos
      if (nombre.getText().isEmpty())
      {
          JOptionPane.showMessageDialog(this, "No se capturó el nombre del Instrumento",
                                          "Mensaje", JOptionPane.WARNING_MESSAGE);
          nombre.requestFocus();
          return;
      }
      
      /*if (numero_reactivos.getText().isEmpty())
      {
          JOptionPane.showMessageDialog(this, "No se capturó el número de reactivos del Instrumento",
                                          "Mensaje", JOptionPane.WARNING_MESSAGE);
          numero_reactivos.requestFocus();
          return;
      }*/       
    
      Datos.Instrumento oInstrumento = new Datos.Instrumento(enlace);    
        
      // El ID lo genera automáticamente la base de datos cuando el registro es nuevo
      int idx;
      idx = (id.getText().isEmpty())?0:Integer.valueOf(id.getText());
      oInstrumento.setInstrumento(idx,
                                  nombre.getText(),
                                  0,
                                  dificultad.getSelectedIndex(),
                                  ((ListaEleccion)egel.getSelectedItem()).id
                                  ); 
      
      if (this.accion.equals("NUEVO"))
      {
        // Se manda escribir a la base de datos
        if (!oInstrumento.Nuevo())
        {
          nombre.requestFocus();
          return;
        }
      }
   
      if (this.accion.equals("EDITAR"))
      {
        // Se manda escribir a la base de datos
        if (!oInstrumento.Editar())
        {
          nombre.requestFocus();
          return;
        }
      }      
    
      if (this.accion.equals("ELIMINAR"))
      {
        // Se manda escribir a la base de datos
        if (!oInstrumento.Eliminar())
        {
          boton_guardar.requestFocus();
          return;
        }
      }
      
      this.dispose();
      padre.cargarTabla();
    }//GEN-LAST:event_boton_guardarActionPerformed

    private void boton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_boton_cancelarActionPerformed

    private void numero_reactivosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numero_reactivosKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
             
         
          if(Character.isLetter(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); 
          } 
    }//GEN-LAST:event_numero_reactivosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Egel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Instrumento().setVisible(true);                               
            }
        });
    }
    
    public void configurarPara(String accion)
    {
        this.accion = accion;
        if (accion.equals("NUEVO"))
        {            
           // limpiarCampos();
           id.setEnabled(false);
        }

        if (accion.equals("EDITAR"))
        {
            habilitarCampos(true);
            id.setEnabled(false);
        }
        
        if (accion.equals("ELIMINAR"))
        {
            habilitarCampos(false);            
        }
         
        // Cargamos los datos de la lista
        Datos.Egel oEgel = new Datos.Egel(enlace);
        DefaultComboBoxModel datos = new DefaultComboBoxModel();
        datos.removeAllElements();
        Vector items = new Vector();
        items.addAll(oEgel.Lista());
        for (int i = 0; i < items.size(); i++)
        {
          datos.addElement(items.get(i));
        }
        egel.setModel(datos);         
    }
    
    public void habilitarCampos(boolean estado)
    {
        egel.setEnabled(estado);
        id.setEditable(estado);
        nombre.setEditable(estado);      
        numero_reactivos.setEditable(estado);
        dificultad.setEnabled(estado);
   }
    
   public void cargarCampos(int idx)
    {
        Datos.Instrumento oInstrumento = new Datos.Instrumento(enlace);
        oInstrumento.Buscar(idx);  
        egel.setSelectedItem(new ListaEleccion(oInstrumento.getIdEgel(),""));
        id.setText(Integer.toString(oInstrumento.getID()));        
        nombre.setText(oInstrumento.getNombre());
        numero_reactivos.setText(String.valueOf(oInstrumento.getNumeroReactivos()));
        dificultad.setSelectedIndex(oInstrumento.getDificultad());
   } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_cancelar;
    private javax.swing.JButton boton_guardar;
    private javax.swing.JComboBox dificultad;
    private javax.swing.JComboBox egel;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lcodigo;
    private javax.swing.JLabel ldescri;
    private javax.swing.JLabel legel;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numero_reactivos;
    // End of variables declaration//GEN-END:variables
}
