/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Catalogos;

import Datos.Conexion;
import Datos.ListaEleccion;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Paul
 */
public class Institucion extends javax.swing.JDialog {
    private String accion;
    public Conexion enlace;
    public Instituciones padre;
    
    /**
     * Creates new form Institucion
     */
    public Institucion() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lcodigo = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        ldescri = new javax.swing.JLabel();
        boton_guardar = new javax.swing.JButton();
        boton_cancelar = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        lentidadmunicipio = new javax.swing.JLabel();
        poblacion = new javax.swing.JTextField();
        lpoblacion = new javax.swing.JLabel();
        municipio = new javax.swing.JComboBox();
        lcontacto = new javax.swing.JLabel();
        contacto = new javax.swing.JComboBox();
        lcolonia = new javax.swing.JLabel();
        colonia = new javax.swing.JTextField();
        lcalle_y_numero = new javax.swing.JLabel();
        calle_y_numero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Institución");
        setMinimumSize(new java.awt.Dimension(580, 200));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setPreferredSize(new java.awt.Dimension(580, 200));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        lcodigo.setText("ID");
        getContentPane().add(lcodigo);
        lcodigo.setBounds(40, 40, 120, 14);

        nombre.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        nombre.setMinimumSize(new java.awt.Dimension(8, 24));
        nombre.setPreferredSize(new java.awt.Dimension(8, 24));
        getContentPane().add(nombre);
        nombre.setBounds(180, 60, 360, 28);

        ldescri.setText("Nombre");
        getContentPane().add(ldescri);
        ldescri.setBounds(180, 40, 310, 14);

        boton_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuardarTodo.png"))); // NOI18N
        boton_guardar.setMnemonic('G');
        boton_guardar.setText("OK");
        boton_guardar.setToolTipText("Guardar registro");
        boton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_guardar);
        boton_guardar.setBounds(270, 510, 130, 40);

        boton_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        boton_cancelar.setMnemonic('C');
        boton_cancelar.setText("Cancelar");
        boton_cancelar.setToolTipText("Cancelar actualización");
        boton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_cancelar);
        boton_cancelar.setBounds(410, 510, 130, 40);

        id.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        id.setMinimumSize(new java.awt.Dimension(8, 24));
        id.setPreferredSize(new java.awt.Dimension(8, 24));
        getContentPane().add(id);
        id.setBounds(40, 60, 120, 28);

        lentidadmunicipio.setText("Entidad Federativa y Municipio");
        getContentPane().add(lentidadmunicipio);
        lentidadmunicipio.setBounds(40, 110, 230, 14);

        poblacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                poblacionKeyTyped(evt);
            }
        });
        getContentPane().add(poblacion);
        poblacion.setBounds(40, 220, 500, 28);

        lpoblacion.setText("Población");
        getContentPane().add(lpoblacion);
        lpoblacion.setBounds(40, 190, 90, 14);

        getContentPane().add(municipio);
        municipio.setBounds(40, 140, 500, 28);

        lcontacto.setText("Contacto");
        getContentPane().add(lcontacto);
        lcontacto.setBounds(40, 420, 100, 14);

        getContentPane().add(contacto);
        contacto.setBounds(40, 450, 500, 28);

        lcolonia.setText("Colonia");
        getContentPane().add(lcolonia);
        lcolonia.setBounds(40, 260, 90, 14);

        colonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coloniaActionPerformed(evt);
            }
        });
        getContentPane().add(colonia);
        colonia.setBounds(40, 290, 500, 28);

        lcalle_y_numero.setText("Calle y Número");
        getContentPane().add(lcalle_y_numero);
        lcalle_y_numero.setBounds(40, 340, 140, 14);
        getContentPane().add(calle_y_numero);
        calle_y_numero.setBounds(40, 370, 500, 28);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-603)/2, (screenSize.height-621)/2, 603, 621);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardarActionPerformed
      // Validamos los datos
      if (nombre.getText().isEmpty())
      {
          JOptionPane.showMessageDialog(this, "No se capturó el nombre de la Institución",
                                          "Mensaje", JOptionPane.WARNING_MESSAGE);
          nombre.requestFocus();
          return;
      }
      
      if (nombre.getText().isEmpty())
      {
          JOptionPane.showMessageDialog(this, "No se capturó la población de la Institución",
                                          "Mensaje", JOptionPane.WARNING_MESSAGE);
          poblacion.requestFocus();
          return;
      }      
           
    
      Datos.Institucion oInstitucion = new Datos.Institucion(enlace);    
        
      // El ID lo genera automáticamente la base de datos cuando el registro es nuevo
      int idx;
      idx = (id.getText().isEmpty())?0:Integer.valueOf(id.getText());
      oInstitucion.setInstitucion(idx,
                                  nombre.getText(),
                                  poblacion.getText(),
                                  colonia.getText(),
                                  calle_y_numero.getText(),                                  
                                  ((ListaEleccion)municipio.getSelectedItem()).getId(),
                                  ((ListaEleccion)contacto.getSelectedItem()).getId()
                                  ); 
      
      if (this.accion.equals("NUEVO"))
      {
        // Se manda escribir a la base de datos
        if (!oInstitucion.Nuevo())
        {
          nombre.requestFocus();
          return;
        }
      }
   
      if (this.accion.equals("EDITAR"))
      {
        // Se manda escribir a la base de datos
        if (!oInstitucion.Editar())
        {
          nombre.requestFocus();
          return;
        }
      }      
    
      if (this.accion.equals("ELIMINAR"))
      {
        // Se manda escribir a la base de datos
        if (!oInstitucion.Eliminar())
        {
          boton_guardar.requestFocus();
          return;
        }
      }
      
      this.dispose();
      padre.cargarTabla();
    }//GEN-LAST:event_boton_guardarActionPerformed

    private void boton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_boton_cancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
    }//GEN-LAST:event_formWindowActivated

    private void poblacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_poblacionKeyTyped
       
    }//GEN-LAST:event_poblacionKeyTyped

    private void coloniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coloniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coloniaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Egel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Institucion().setVisible(true);                               
            }
        });
    }
    
    public void configurarPara(String accion)
    {
        this.accion = accion;
        if (accion.equals("NUEVO"))
        {            
           // limpiarCampos();
           id.setEnabled(false);
        }

        if (accion.equals("EDITAR"))
        {
            habilitarCampos(true);
            id.setEnabled(false);
        }
        
        if (accion.equals("ELIMINAR"))
        {
            habilitarCampos(false);            
        }
         
        
        // Cargamos los datos de la lista de municipios
        Datos.Municipio oMunicipio = new Datos.Municipio(enlace);
        DefaultComboBoxModel datos_municipio = new DefaultComboBoxModel();
        Vector items_municipio = new Vector();
        datos_municipio.removeAllElements();
        items_municipio.removeAllElements();
        
        items_municipio.addAll(oMunicipio.Lista());
        for (int i = 0; i < items_municipio.size(); i++)
        {
          datos_municipio.addElement(items_municipio.get(i));
        }
        municipio.setModel(datos_municipio);    
        
        
        // Cargamos los datos de la lista de contactos
        Datos.Contacto oContacto = new Datos.Contacto(enlace);
        DefaultComboBoxModel datos_contacto = new DefaultComboBoxModel();
        Vector items_contacto = new Vector();
        datos_contacto.removeAllElements();
        items_contacto.removeAllElements();
        items_contacto.addAll(oContacto.Lista());
        for (int i = 0; i < items_contacto.size(); i++)
        {
          datos_contacto.addElement(items_contacto.get(i));
        }
        contacto.setModel(datos_contacto);   
    }
    
    public void habilitarCampos(boolean estado)
    {        
        id.setEditable(estado);
        nombre.setEditable(estado);  
        poblacion.setEditable(estado);  
        colonia.setEditable(estado);
        calle_y_numero.setEditable(estado);
        contacto.setEnabled(estado);
        municipio.setEnabled(estado);
   }
    
   public void cargarCampos(int idx)
    {
        Datos.Institucion oInstitucion = new Datos.Institucion(enlace);
        oInstitucion.Buscar(idx);  
        id.setText(Integer.toString(oInstitucion.getID()));        
        nombre.setText(oInstitucion.getNombre());
        poblacion.setText(oInstitucion.getPoblacion());
        colonia.setText(oInstitucion.getColonia());
        calle_y_numero.setText(oInstitucion.getCalle_y_Numero());
        municipio.setSelectedItem(new ListaEleccion(oInstitucion.getMunicipio_Id(),""));
        contacto.setSelectedItem(new ListaEleccion(oInstitucion.getContacto_Id(),""));
   } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_cancelar;
    private javax.swing.JButton boton_guardar;
    private javax.swing.JTextField calle_y_numero;
    private javax.swing.JTextField colonia;
    private javax.swing.JComboBox contacto;
    private javax.swing.JTextField id;
    private javax.swing.JLabel lcalle_y_numero;
    private javax.swing.JLabel lcodigo;
    private javax.swing.JLabel lcolonia;
    private javax.swing.JLabel lcontacto;
    private javax.swing.JLabel ldescri;
    private javax.swing.JLabel lentidadmunicipio;
    private javax.swing.JLabel lpoblacion;
    private javax.swing.JComboBox municipio;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField poblacion;
    // End of variables declaration//GEN-END:variables
}
